# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Scrape Top Grossing Movies

on:
  schedule:
    - cron: '49 * * * *'

jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo content
        uses: actions/checkout@v2
        
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Fetch Top Grossing Movies
        run: |
          scrapy crawl boxofficemojo
      - name: Commit and push if it changed
        run: |
          git config user.name "Automated"
          git config user.email "actions@users.noreply.github.com"
          git add data/topgrossingmovies.json
          timestamp=$(date -u)
          git diff --quiet data/topgrossingmovies.json || (git commit -m "Latest data: ${timestamp} - Update data/topgrossingmovies.json" && git push)
